image: node:10

before_script:
  - ls

stages:
    - build
    - test

test:
  stage: test
  script:
    - echo "Running tests"
    - cd atour-backend
    - npm install --production
    - npm run test

build-backend:
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:dind
  script:
    - echo "Building the app"
    - cd atour-backend
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/atour/atour/backend:${CI_COMMIT_REF_NAME} .
    - docker push registry.gitlab.com/atour/atour/backend:${CI_COMMIT_REF_NAME}

